layout_spectrum: 0.10621924209408462
typography_spectrum: 0.1871458888053894
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.0692062743473798
  lightness: 0.8598720645532012
  saturation: 0.3539958766195923
  rhythmicContrast: 0.6518727580551058
content_rating:
  adult: false
opengraph:
  type: ''
  appId: ''
author:
  name: ''
  url: ''
  email: ''
name: archmaterius
navigation:
  - name: Service
    id: 7abf16fc-fd30-41db-bcea-d85b15eb211e
    type: content
title: ''
