typography_spectrum: 0.20576539542526007
content_rating:
  adult: false
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.9846511746291071
  lightness: 0.2899325645994395
  saturation: 0.7493881483096629
  rhythmicContrast: 0.3000107007101178
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.5134039795957506
author:
  name: ''
  url: ''
  email: ''
name: archmaterius
navigation:
  - name: Service
    id: 7abf16fc-fd30-41db-bcea-d85b15eb211e
    type: content
title: ''
