typography_spectrum: 0.43657768657431006
content_rating:
  adult: false
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.364086352288723
  lightness: 0.38707653037272394
  saturation: 0.9669014730025083
  rhythmicContrast: 0.10483296308666468
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.0768913405481726
author:
  name: ''
  url: ''
  email: ''
name: archmaterius
navigation:
  - name: Service
    id: 7abf16fc-fd30-41db-bcea-d85b15eb211e
    type: content
title: ''
