layout_spectrum: 0.49974705395288765
typography_spectrum: 0.5225425832904875
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.483775194035843
  lightness: 0.4203655633609742
  saturation: 0.3028674500528723
  rhythmicContrast: 0.617360427044332
content_rating:
  adult: false
opengraph:
  type: ''
  appId: ''
author:
  name: ''
  url: ''
  email: ''
name: archmaterius
navigation:
  - name: Service
    id: 7abf16fc-fd30-41db-bcea-d85b15eb211e
    type: content
title: ''
